name: CI

on:
  push:
    paths:
      - "back-end/**"
      - "front-end/**"
    branches:
      - main
      - develop
      - "*"
  pull_request:
    paths:
      - "back-end/**"
      - "front-end/**"
    branches:
      - main
      - develop
      - "*"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Backend setup and tests
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: back-end/package-lock.json

      - name: Install dependencies (Backend)
        working-directory: back-end
        run: npm ci

      - name: Run linter (Backend)
        working-directory: back-end
        run: npm run lint

      - name: Run tests (Backend)
        working-directory: back-end
        run: npm test

      # Frontend setup and tests
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: front-end/package-lock.json

      - name: Install dependencies (Frontend)
        working-directory: front-end
        run: npm ci

      - name: Run linter (Frontend)
        working-directory: front-end
        run: npm run lint

      - name: Run tests (Frontend)
        working-directory: front-end
        run: npm test
